version: "3.7"

services:
    data_base:
        image: postgres:10.5
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword

    flask-api:
        container_name: api-login
        restart: always
        build:
            context: ./api/
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - FLASK_ENV=development
            - KAFKA_ADVERTISED_HOST_NAME=kafka
        ports:
            - "3000:80"
        volumes:
            - ./api:/usr/src/app
            - ./storage:/tmp/storage
        depends_on:
            - "data_base"
            - "kafka"

    flask-api-blocked:
        container_name: api-blocked
        restart: always
        build:
            context: ./api-blocked/
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - FLASK_ENV=development
            - KAFKA_ADVERTISED_HOST_NAME=kafka
        ports:
            - "5000:5000"
            - "5004:5004"
        volumes:
            - ./api-blocked:/usr/src/app
            - ./storage:/tmp/storage
        depends_on:
            - "data_base"
            - "kafka"
        command: python app.py
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_CREATE_TOPICS: "login:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - "zookeeper"
